### ISSUE TITLE
New feature request: Support users to add executable script types in the yaml configuration file.

### ISSUE THREAD

**Issue by xyyy1420** [open-rust-initiative/dagrs#16]
# Summary

Currently, only the custom Parser interface is supported. If you want to add a new script type based on the executable script type supported by dagrs, you must rewrite the part of the execution script that dagrs has implemented, which is not convenient.

# Background

When I use dagrs to write a build platform, I want to use the original function of dagrs to execute shell scripts, but I also want to support other types of scripts. At this time, I found that I can only rewrite the Parser interface, and dagrs has been implemented I have to rewrite the old function myself

# Outcome

An interface that can be called by users to support filling new script types and their execution methods into dagrs

**Comment by genedna** [comment]
@QIUZHILEI @xyyy1420 ,

The `parse_one(&self, id: &str, item: &Yaml)` function in `yaml_parser.rs` currently supports only the `sh` and `deno` script types. Both types implement the `Action` trait:

```Rust
pub trait Action {
    /// The specific behavior to be performed by the task.
    fn run(&self, input: Input, env: Arc<EnvVar>) -> Result<Output, RunningError>;
}
```

To enhance support for custom script types in the YAML, I propose modifying the `parse_one` function by adding an optional `action: Option<Box<dyn Action>>` parameter. The default value will be `None`, allowing for backward compatibility with existing code:

```Rust
fn parse_one(&self, id: &str, item: &Yaml, action: Option<Box<dyn Action>>) -> Result<Task, ParsingError> {
    // ...
}
```

When an `action` is provided, the custom script type can replace the hardcoded `sh` and `deno` types. This approach enables users to extend the YAML parser with customized script types without modifying the existing implementation:

```Rust
impl Action for CustomScriptType {
    fn run(&self, input: Input, env: Arc<EnvVar>) -> Result<Output, RunningError> {
        // Implement custom script execution logic here
    }
}

let custom_action: Box<dyn Action> = Box::new(CustomScriptType::new());
let result = yaml_parser.parse_one("task_id", &yaml_content, Some(custom_action));
```

By introducing the optional `action` parameter, users can extend the YAML parser's functionality to support custom script types more conveniently.
