### ISSUE TITLE
Ability to parse a string

### ISSUE THREAD

**Issue by kdesjard** [open-rust-initiative/dagrs#31]
It would be nice to be able to parse the tasks from a string instead of a file.  I'm not sure how to do this without breaking the current interface or duplicating a lot of code.  Also possible, but may not be desirable is to have parse_tasks to detect whether the file is actually a file and if not, then treat it as a string.

**Comment by genedna** [comment]
@kdesjard,

Thank you for raising the issue about parsing tasks from a string. I understand the potential challenges in implementing this without disrupting the current interface or duplicating code.

To better assist with this, what format do you envision for the string? Are you considering it a bash script or some other interpreted language program?

**Comment by kdesjard** [comment]
For my particular use case, I wanted to be able to parse a string in yaml format.  The string would come from a rendered template.

**Comment by genedna** [comment]
@kdesjard,

Could you provide a sample string in the YAML format that you mentioned? It would help us understand the expected input and how to integrate it into dagrs best.

**Comment by kdesjard** [comment]
Any correctly formatted yaml.

eg:
```rust
fn yaml_task_correct_execute_from_string() {
    let _initialized = log::init_logger(LogLevel::Info, None);
        let yaml_str = r#"
dagrs:
  a:
    name: "Task 1"
    cmd: echo Testing123
  b:
    name: "Task 2"
    after: [ a ]
    cmd: echo Testing2_123
"#;
    let mut job = Dag::with_yaml_from_str(yaml_str,HashMap::new()).unwrap();
    assert!(job.start().unwrap());
}
```

**Comment by kdesjard** [comment]
YAML config file reading from str merged.
